// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inserts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (
        alignment_description,
        alignment_type,
        character_class_key,
        charisma,
        constitution,
        dexterity,
        hit_points,
        intelligence,
        name,
        race_move_key,
        strength,
        wisdom
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12
    )
RETURNING id
`

type CreateCharacterParams struct {
	AlignmentDescription string
	AlignmentType        string
	CharacterClassKey    string
	Charisma             int32
	Constitution         int32
	Dexterity            int32
	HitPoints            int32
	Intelligence         int32
	Name                 string
	RaceMoveKey          string
	Strength             int32
	Wisdom               int32
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.AlignmentDescription,
		arg.AlignmentType,
		arg.CharacterClassKey,
		arg.Charisma,
		arg.Constitution,
		arg.Dexterity,
		arg.HitPoints,
		arg.Intelligence,
		arg.Name,
		arg.RaceMoveKey,
		arg.Strength,
		arg.Wisdom,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createLook = `-- name: CreateLook :one
INSERT INTO looks (character_id, look_type, value)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateLookParams struct {
	CharacterID pgtype.UUID
	LookType    string
	Value       string
}

func (q *Queries) CreateLook(ctx context.Context, arg CreateLookParams) (int32, error) {
	row := q.db.QueryRow(ctx, createLook, arg.CharacterID, arg.LookType, arg.Value)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createMoveCreationOptionChoice = `-- name: CreateMoveCreationOptionChoice :one
INSERT INTO move_creation_option_choices (
        character_id,
        choice_index,
        move_key,
        option_key
    )
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateMoveCreationOptionChoiceParams struct {
	CharacterID pgtype.UUID
	ChoiceIndex int32
	MoveKey     string
	OptionKey   string
}

func (q *Queries) CreateMoveCreationOptionChoice(ctx context.Context, arg CreateMoveCreationOptionChoiceParams) (int32, error) {
	row := q.db.QueryRow(ctx, createMoveCreationOptionChoice,
		arg.CharacterID,
		arg.ChoiceIndex,
		arg.MoveKey,
		arg.OptionKey,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
