// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_character.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCharacter = `-- name: InsertCharacter :one
INSERT INTO characters (
        alignment_description,
        alignment_type,
        character_class_key,
        charisma,
        constitution,
        dexterity,
        hit_points,
        intelligence,
        name,
        race_move_key,
        strength,
        wisdom
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12
    )
RETURNING id
`

type InsertCharacterParams struct {
	AlignmentDescription string
	AlignmentType        string
	CharacterClassKey    string
	Charisma             int32
	Constitution         int32
	Dexterity            int32
	HitPoints            int32
	Intelligence         int32
	Name                 string
	RaceMoveKey          string
	Strength             int32
	Wisdom               int32
}

func (q *Queries) InsertCharacter(ctx context.Context, arg InsertCharacterParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertCharacter,
		arg.AlignmentDescription,
		arg.AlignmentType,
		arg.CharacterClassKey,
		arg.Charisma,
		arg.Constitution,
		arg.Dexterity,
		arg.HitPoints,
		arg.Intelligence,
		arg.Name,
		arg.RaceMoveKey,
		arg.Strength,
		arg.Wisdom,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
