// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_move_creation_option_choice.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMoveCreationOptionChoice = `-- name: InsertMoveCreationOptionChoice :one
INSERT INTO move_creation_option_choices (
        character_id,
        choice_index,
        move_key,
        option_key
    )
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertMoveCreationOptionChoiceParams struct {
	CharacterID pgtype.UUID
	ChoiceIndex int32
	MoveKey     string
	OptionKey   string
}

func (q *Queries) InsertMoveCreationOptionChoice(ctx context.Context, arg InsertMoveCreationOptionChoiceParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertMoveCreationOptionChoice,
		arg.CharacterID,
		arg.ChoiceIndex,
		arg.MoveKey,
		arg.OptionKey,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
