// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_look.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertLook = `-- name: InsertLook :one
INSERT INTO looks (character_id, look_type, value)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertLookParams struct {
	CharacterID pgtype.UUID
	LookType    string
	Value       string
}

func (q *Queries) InsertLook(ctx context.Context, arg InsertLookParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertLook, arg.CharacterID, arg.LookType, arg.Value)
	var id int32
	err := row.Scan(&id)
	return id, err
}
