// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: load_looks.sql

package db

import (
	"context"
)

const loadLooks = `-- name: LoadLooks :many
SELECT character_id,
    id,
    look_type,
    value
FROM looks
WHERE id = ANY ($1::int [])
`

func (q *Queries) LoadLooks(ctx context.Context, dollar_1 []int32) ([]Look, error) {
	rows, err := q.db.Query(ctx, loadLooks, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Look
	for rows.Next() {
		var i Look
		if err := rows.Scan(
			&i.CharacterID,
			&i.ID,
			&i.LookType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
