// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: load_characters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const loadCharacters = `-- name: LoadCharacters :many
SELECT character_class_key,
    alignment_description,
    alignment_type,
    charisma,
    constitution,
    dexterity,
    hit_points,
    id,
    intelligence,
    name,
    race_move_key,
    strength,
    wisdom
FROM characters
WHERE id = ANY ($1::uuid [])
`

type LoadCharactersRow struct {
	CharacterClassKey    string
	AlignmentDescription string
	AlignmentType        string
	Charisma             int32
	Constitution         int32
	Dexterity            int32
	HitPoints            int32
	ID                   pgtype.UUID
	Intelligence         int32
	Name                 string
	RaceMoveKey          string
	Strength             int32
	Wisdom               int32
}

func (q *Queries) LoadCharacters(ctx context.Context, dollar_1 []pgtype.UUID) ([]LoadCharactersRow, error) {
	rows, err := q.db.Query(ctx, loadCharacters, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadCharactersRow
	for rows.Next() {
		var i LoadCharactersRow
		if err := rows.Scan(
			&i.CharacterClassKey,
			&i.AlignmentDescription,
			&i.AlignmentType,
			&i.Charisma,
			&i.Constitution,
			&i.Dexterity,
			&i.HitPoints,
			&i.ID,
			&i.Intelligence,
			&i.Name,
			&i.RaceMoveKey,
			&i.Strength,
			&i.Wisdom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
