// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: load_move_creation_option_choice.sql

package db

import (
	"context"
)

const loadMoveCreationOptionChoice = `-- name: LoadMoveCreationOptionChoice :many
SELECT character_id,
    choice_index,
    id,
    move_key,
    option_key
FROM move_creation_option_choices
WHERE id = ANY ($1::int [])
`

func (q *Queries) LoadMoveCreationOptionChoice(ctx context.Context, dollar_1 []int32) ([]MoveCreationOptionChoice, error) {
	rows, err := q.db.Query(ctx, loadMoveCreationOptionChoice, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MoveCreationOptionChoice
	for rows.Next() {
		var i MoveCreationOptionChoice
		if err := rows.Scan(
			&i.CharacterID,
			&i.ChoiceIndex,
			&i.ID,
			&i.MoveKey,
			&i.OptionKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
