// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Character struct {
	AlignmentDescription string
	AlignmentType        string
	CharacterClassKey    string
	Charisma             int32
	Constitution         int32
	Dexterity            int32
	HitPoints            int32
	ID                   pgtype.UUID
	Intelligence         int32
	Name                 string
	RaceMoveKey          string
	Strength             int32
	Wisdom               int32
}

type Look struct {
	CharacterID pgtype.UUID
	ID          int32
	LookType    string
	Value       string
}

type MoveCreationOptionChoice struct {
	CharacterID pgtype.UUID
	ChoiceIndex int32
	ID          int32
	MoveKey     string
	OptionKey   string
}
