// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_all_characters.sql

package db

import (
	"context"
)

const selectAllCharacters = `-- name: SelectAllCharacters :many
SELECT alignment_description,
    alignment_type,
    character_class_key,
    charisma,
    constitution,
    dexterity,
    hit_points,
    id,
    intelligence,
    name,
    race_move_key,
    strength,
    wisdom
FROM characters
`

func (q *Queries) SelectAllCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.Query(ctx, selectAllCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.AlignmentDescription,
			&i.AlignmentType,
			&i.CharacterClassKey,
			&i.Charisma,
			&i.Constitution,
			&i.Dexterity,
			&i.HitPoints,
			&i.ID,
			&i.Intelligence,
			&i.Name,
			&i.RaceMoveKey,
			&i.Strength,
			&i.Wisdom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
