// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_looks_by_character.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const selectLooksByCharacter = `-- name: SelectLooksByCharacter :many
SELECT character_id,
    id,
    look_type,
    value
FROM looks
WHERE character_id = $1::uuid
`

func (q *Queries) SelectLooksByCharacter(ctx context.Context, dollar_1 pgtype.UUID) ([]Look, error) {
	rows, err := q.db.Query(ctx, selectLooksByCharacter, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Look
	for rows.Next() {
		var i Look
		if err := rows.Scan(
			&i.CharacterID,
			&i.ID,
			&i.LookType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
