// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_move_creation_option_choices_by_character.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const selectMoveCreationOptionChoicesByCharacter = `-- name: SelectMoveCreationOptionChoicesByCharacter :many
SELECT character_id,
    choice_index,
    id,
    move_key,
    option_key
FROM move_creation_option_choices
WHERE character_id = $1::uuid
`

func (q *Queries) SelectMoveCreationOptionChoicesByCharacter(ctx context.Context, dollar_1 pgtype.UUID) ([]MoveCreationOptionChoice, error) {
	rows, err := q.db.Query(ctx, selectMoveCreationOptionChoicesByCharacter, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MoveCreationOptionChoice
	for rows.Next() {
		var i MoveCreationOptionChoice
		if err := rows.Scan(
			&i.CharacterID,
			&i.ChoiceIndex,
			&i.ID,
			&i.MoveKey,
			&i.OptionKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
