import "./index.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ApolloWrapper } from "@/components/ApolloWrapper";
import Link from "next/link";
import { FC, PropsWithChildren } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <ApolloWrapper>
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-black min-h-full flex flex-col text-white">
        <header className="bg-neutral-900 p-4">
          <nav>
            <Link href="/">
              <h1 className="font-bold text-xl">Dungeon World AI</h1>
            </Link>
          </nav>
        </header>
        <main className="flex-1 p-4">{children}</main>
      </body>
    </html>
  </ApolloWrapper>
);

export default RootLayout;
