// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/google/uuid"
)

// A type representing a character's ability score, including the base score and the derived modifier.
type AbilityScore struct {
	// The ability this score belongs to.
	Ability Ability `json:"ability"`
	// The numeric modifier to use when rolling.
	Modifier int32 `json:"modifier"`
	// The numeric score for this ability.
	Score int32 `json:"score"`
}

// Input for setting an ability score when creating a character.
type AbilityScoreInput struct {
	// The ability this score belongs to.
	Ability Ability `json:"ability"`
	// The numeric score for this ability.
	Score int32 `json:"score"`
}

// An example of an alignment a player may use
type AlignmentTemplate struct {
	// The alignment type
	Alignment string `json:"alignment"`
	// A description of what their goals are
	Description string `json:"description"`
}

// A player character in the game.
type Character struct {
	// The character's six core ability scores, one for each ability.
	Abilities []*AbilityScore `json:"abilities"`
	// Unique identifier for the character.
	ID string `json:"id"`
	// The character's name.
	Name string `json:"name"`
	// The character's appearance choices, one per look type.
	Looks []*Look `json:"looks"`
}

// A playable character class as defined by the Dungeon World ruleset (e.g. Fighter, Wizard).
type CharacterClass struct {
	// Moves available when choosing an alignment for this class.
	AlignmentTemplates []*AlignmentTemplate `json:"alignmentTemplates"`
	// Example bonds templates.
	Bonds []string `json:"bonds"`
	// The die used for damage rolls (e.g. 8 for d8).
	DamageDie int32 `json:"damageDie"`
	// Base hit points before adding Constitution modifier.
	HpBase int32 `json:"hpBase"`
	// Unique key for this class.
	Key string `json:"key"`
	// Examples of looks commonly associated with this class.
	LookExamples []*LookExample `json:"lookExamples"`
	// Human-readable class name.
	Name string `json:"name"`
	// Moves available when choosing a race for this class.
	RaceMoves []*Move `json:"raceMoves"`
	// Moves every character of this class begins with.
	StartingMoves []*Move `json:"startingMoves"`
}

// Namespace for character mutations.
type CharacterMutation struct {
	// Creates a new character and returns it.
	Create *Character `json:"create"`
}

// Namespace for character queries.
type CharacterQuery struct {
	// Returns all characters.
	All []*Character `json:"all"`
	// Returns a single character by ID, or null if not found.
	ByID *Character `json:"byId"`
}

// Input for creating a new character.
type CreateCharacterInput struct {
	Abilities []*AbilityScoreInput `json:"abilities"`
	// The character's name.
	Name string `json:"name"`
	// One look selection per look type.
	Looks []*NewLookInput `json:"looks"`
}

// An active game session linking a character to a scenario.
type Game struct {
	// Unique identifier for the game.
	ID string `json:"id"`
	// Human-readable name for this game session.
	Name string `json:"name"`
	// ID of the character playing in this game.
	CharacterID string `json:"characterId"`
	// Key of the scenario being played.
	ScenarioKey string `json:"scenarioKey"`
}

// Namespace for game mutations.
type GameMutation struct {
	// Creates a new game session and returns it.
	Create *Game `json:"create"`
}

// Namespace for game queries.
type GameQuery struct {
	// Returns all games.
	All []*Game `json:"all"`
	// Returns a single game by ID, or null if not found.
	ByID *Game `json:"byId,omitempty"`
}

// A single appearance choice made for a character.
type Look struct {
	// Unique identifier for this look entry.
	ID string `json:"id"`
	// The chosen appearance value (e.g. 'Wild Eyes').
	Value string `json:"value"`
	// The look type this value belongs to (e.g. Eyes, Hair). Null if the look type no longer exists.
	LookType *LookType `json:"lookType,omitempty"`
}

type LookExample struct {
	// The type of look (e.g. clothing, hair, etc.)
	Type string `json:"type"`
	// Examples of looks for this type.
	Examples []string `json:"examples"`
}

// A category of appearance choice available when creating a character (e.g. Eyes, Hair, Body).
type LookType struct {
	// Unique key for this look type.
	Key string `json:"key"`
	// Human-readable name (e.g. 'Eyes').
	Name string `json:"name"`
	// Example values players can choose from (e.g. 'Wild Eyes', 'Sunken Eyes').
	Examples []string `json:"examples"`
}

// A message in the game's conversation history.
type Message struct {
	// Unique identifier for the message.
	ID uuid.UUID `json:"id"`
	// Who sent the message (e.g. the player's character name or 'assistant').
	Author string `json:"author"`
	// The message text.
	Content string `json:"content"`
	// When the message was sent.
	Datetime string `json:"datetime"`
}

// Namespace for message mutations.
type MessageMutation struct {
	// Sends a player message and returns the resulting assistant reply.
	Send *Message `json:"send"`
}

// Namespace for message queries.
type MessageQuery struct {
	// Returns all messages in the current game's conversation.
	All []*Message `json:"all"`
}

// An action or ability a character can perform, as defined by the Dungeon World ruleset.
type Move struct {
	// Unique key for this move.
	Key string `json:"key"`
	// Human-readable name of the move.
	Name string `json:"name"`
	// The trigger for when a move is used.
	Trigger string `json:"trigger"`
	// Category of the move (e.g. 'starting', 'alignment', 'race').
	Type string `json:"type"`
}

// Namespace for move queries.
type MoveQuery struct {
	// Returns all moves.
	All []*Move `json:"all"`
	// Returns a single move by key, or null if not found.
	ByKey *Move `json:"byKey"`
}

type Mutation struct {
}

// A single look selection when creating a character.
type NewLookInput struct {
	// The key of the look type being set.
	LookTypeKey string `json:"lookTypeKey"`
	// The chosen appearance value.
	Value string `json:"value"`
}

type Query struct {
}

// A pre-written adventure scenario that can be played.
type Scenario struct {
	// Unique key for this scenario.
	Key string `json:"key"`
	// Human-readable scenario title.
	Name string `json:"name"`
	// A short summary of the scenario's premise.
	Description string `json:"description"`
}

// Namespace for scenario queries.
type ScenarioQuery struct {
	// Returns all available scenarios.
	All []*Scenario `json:"all"`
	// Returns a single scenario by key, or null if not found.
	ByKey *Scenario `json:"byKey,omitempty"`
}

// The six core ability scores used for all rolls and derived stats in Dungeon World.
type Ability string

const (
	// Charisma (CHA) — used for social manipulation, bard magic, and paladin healing.
	AbilityCharisma Ability = "CHARISMA"
	// Constitution (CON) — used for HP calculation and endurance rolls.
	AbilityConstitution Ability = "CONSTITUTION"
	// Dexterity (DEX) — used for ranged attacks, agility, and traps.
	AbilityDexterity Ability = "DEXTERITY"
	// Intelligence (INT) — used for knowledge checks and arcane magic (Wizard).
	AbilityIntelligence Ability = "INTELLIGENCE"
	// Strength (STR) — used for melee attacks and feats of force.
	AbilityStrength Ability = "STRENGTH"
	// Wisdom (WIS) — used for perception, divine magic (Cleric), and nature magic (Druid/Ranger).
	AbilityWisdom Ability = "WISDOM"
)

var AllAbility = []Ability{
	AbilityCharisma,
	AbilityConstitution,
	AbilityDexterity,
	AbilityIntelligence,
	AbilityStrength,
	AbilityWisdom,
}

func (e Ability) IsValid() bool {
	switch e {
	case AbilityCharisma, AbilityConstitution, AbilityDexterity, AbilityIntelligence, AbilityStrength, AbilityWisdom:
		return true
	}
	return false
}

func (e Ability) String() string {
	return string(e)
}

func (e *Ability) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Ability(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Ability", str)
	}
	return nil
}

func (e Ability) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Ability) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Ability) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
