package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"maps"

	"github.com/deepconcern/dwai/dwai-api/graph/model"
)

// StartingGear is the resolver for the startingGear field.
func (r *characterClassResolver) StartingGear(ctx context.Context, obj *model.CharacterClass) (*model.StartingGear, error) {
	c := (*r.CharacterClasses)[obj.Key]

	return c.StartingGear.ToObject(r.Equipment, r.TagDefinitions), nil
}

// All is the resolver for the all field.
func (r *characterClassQueryResolver) All(ctx context.Context, obj *model.CharacterClassQuery) ([]*model.CharacterClass, error) {
	characterClasses := make([]*model.CharacterClass, 0)

	for c := range maps.Values(*r.CharacterClasses) {
		characterClasses = append(characterClasses, c.ToObject())
	}

	return characterClasses, nil
}

// ByKey is the resolver for the byKey field.
func (r *characterClassQueryResolver) ByKey(ctx context.Context, obj *model.CharacterClassQuery, key string) (*model.CharacterClass, error) {
	c, ok := (*r.CharacterClasses)[key]
	if ok {
		return c.ToObject(), nil
	}

	return nil, errors.New("No model found")
}

// CharacterClass returns CharacterClassResolver implementation.
func (r *Resolver) CharacterClass() CharacterClassResolver { return &characterClassResolver{r} }

// CharacterClassQuery returns CharacterClassQueryResolver implementation.
func (r *Resolver) CharacterClassQuery() CharacterClassQueryResolver {
	return &characterClassQueryResolver{r}
}

type characterClassResolver struct{ *Resolver }
type characterClassQueryResolver struct{ *Resolver }
