package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/deepconcern/dwai/dwai-api/graph/model"
	"github.com/deepconcern/dwai/dwai-api/models"
)

// Modifier is the resolver for the modifier field.
func (r *abilityScoreResolver) Modifier(ctx context.Context, obj *model.AbilityScore) (int32, error) {
	if obj.Score < 4 {
		return -3, nil
	}

	if obj.Score < 6 {
		return -2, nil
	}

	if obj.Score < 9 {
		return -1, nil
	}

	if obj.Score < 13 {
		return 0, nil
	}

	if obj.Score < 16 {
		return 1, nil
	}

	if obj.Score < 18 {
		return 2, nil
	}

	return 3, nil
}

// Create is the resolver for the create field.
func (r *characterMutationResolver) Create(ctx context.Context, obj *model.CharacterMutation, input model.CreateCharacterInput) (*model.Character, error) {
	// Create character in database

	var id string
	if err := r.DbPool.QueryRow(context.Background(), "INSERT INTO characters (name) VALUES ($1) RETURNING id", input.Name).Scan(&id); err != nil {
		fmt.Printf("Error creating character: %s\n", err)
		return nil, err
	}

	// Build character and prime the loader cache

	characterModel := &models.CharacterModel{
		ID:   id,
		Name: input.Name,
	}

	r.Loaders.CharacterLoader.Prime(characterModel.ID, characterModel)

	return characterModel.ToObject(), nil
}

// All is the resolver for the all field.
func (r *characterQueryResolver) All(ctx context.Context, obj *model.CharacterQuery) ([]*model.Character, error) {
	// Database query for all characters

	rows, err := r.DbPool.Query(context.Background(), "SELECT id, name FROM characters")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	// Extract characters from rows

	characterModels := make([]*models.CharacterModel, 0)
	for rows.Next() {
		var characterModel models.CharacterModel
		if err := rows.Scan(&characterModel.ID, &characterModel.Name); err != nil {
			return nil, err
		}
		characterModels = append(characterModels, &characterModel)
	}

	// Build characters and prime the loader cache

	characters := make([]*model.Character, len(characterModels))
	for i, characterModel := range characterModels {
		r.Loaders.CharacterLoader.Prime(characterModel.ID, characterModel)
		characters[i] = characterModel.ToObject()
	}

	return characters, nil
}

// ByID is the resolver for the byId field.
func (r *characterQueryResolver) ByID(ctx context.Context, obj *model.CharacterQuery, id string) (*model.Character, error) {
	m, err := r.Loaders.CharacterLoader.Load(ctx, id)
	if err != nil {
		return nil, err
	}

	return m.ToObject(), nil
}

// AbilityScore returns AbilityScoreResolver implementation.
func (r *Resolver) AbilityScore() AbilityScoreResolver { return &abilityScoreResolver{r} }

// CharacterMutation returns CharacterMutationResolver implementation.
func (r *Resolver) CharacterMutation() CharacterMutationResolver {
	return &characterMutationResolver{r}
}

// CharacterQuery returns CharacterQueryResolver implementation.
func (r *Resolver) CharacterQuery() CharacterQueryResolver { return &characterQueryResolver{r} }

type abilityScoreResolver struct{ *Resolver }
type characterMutationResolver struct{ *Resolver }
type characterQueryResolver struct{ *Resolver }
