package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"strings"
	"unicode/utf8"

	"github.com/deepconcern/dwai/dwai-api/graph/model"
)

// All is the resolver for the all field.
func (r *lookTypeQueryResolver) All(ctx context.Context, obj *model.LookTypeQuery) ([]*model.LookType, error) {
	lookTypeMap := make(map[string][]string)

	for _, class := range *r.CharacterClasses {
		for lookType, examples := range class.Looks {
			existingExamples, ok := lookTypeMap[lookType]
			if !ok {
				existingExamples = []string{}
			}
			lookTypeMap[lookType] = append(existingExamples, examples...)
		}
	}

	lookTypes := make([]*model.LookType, 0, len(lookTypeMap))
	for lookType, examples := range lookTypeMap {
		// Capitalize the first letter of the look type for display purposes
		r, size := utf8.DecodeRuneInString(lookType)
		name := strings.ToUpper(string(r)) + lookType[size:]

		lookTypes = append(lookTypes, &model.LookType{
			Examples: examples,
			Key:      lookType,
			Name:     name,
		})
	}

	return lookTypes, nil
}

// LookTypeQuery returns LookTypeQueryResolver implementation.
func (r *Resolver) LookTypeQuery() LookTypeQueryResolver { return &lookTypeQueryResolver{r} }

type lookTypeQueryResolver struct{ *Resolver }
