package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"maps"

	"github.com/deepconcern/dwai/dwai-api/graph/model"
)

// All is the resolver for the all field.
func (r *moveQueryResolver) All(ctx context.Context, obj *model.MoveQuery) ([]*model.Move, error) {
	moves := make([]*model.Move, 0)

	for m := range maps.Values(*r.PlayerMoves) {
		moves = append(moves, m.ToObject())
	}

	return moves, nil
}

// ByKey is the resolver for the byKey field.
func (r *moveQueryResolver) ByKey(ctx context.Context, obj *model.MoveQuery, key string) (*model.Move, error) {
	m, ok := (*r.PlayerMoves)[key]

	if ok {
		return m.ToObject(), nil
	}

	return nil, errors.New("No model found")
}

// ByType is the resolver for the byType field.
func (r *moveQueryResolver) ByType(ctx context.Context, obj *model.MoveQuery, typeArg string) ([]*model.Move, error) {
	moves := make([]*model.Move, 0)

	for m := range maps.Values(*r.PlayerMoves) {
		if m.Type == typeArg {
			moves = append(moves, m.ToObject())
		}
	}

	return moves, nil
}

// MoveQuery returns MoveQueryResolver implementation.
func (r *Resolver) MoveQuery() MoveQueryResolver { return &moveQueryResolver{r} }

type moveQueryResolver struct{ *Resolver }
