package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"os"

	"github.com/deepconcern/dwai/dwai-api/graph/model"
)

// Characters is the resolver for the characters field.
func (r *mutationResolver) Characters(ctx context.Context) (*model.CharacterMutation, error) {
	return &model.CharacterMutation{}, nil
}

// Games is the resolver for the games field.
func (r *mutationResolver) Games(ctx context.Context) (*model.GameMutation, error) {
	return &model.GameMutation{}, nil
}

// Messages is the resolver for the messages field.
func (r *mutationResolver) Messages(ctx context.Context) (*model.MessageMutation, error) {
	return &model.MessageMutation{}, nil
}

// APIVersion is the resolver for the apiVersion field.
func (r *queryResolver) APIVersion(ctx context.Context) (string, error) {
	apiVersion := os.Getenv("API_VERSION")

	if apiVersion == "" {
		return "local", nil
	}

	return apiVersion, nil
}

// CharacterClasses is the resolver for the characterClasses field.
func (r *queryResolver) CharacterClasses(ctx context.Context) (*model.CharacterClassQuery, error) {
	return &model.CharacterClassQuery{}, nil
}

// Characters is the resolver for the characters field.
func (r *queryResolver) Characters(ctx context.Context) (*model.CharacterQuery, error) {
	return &model.CharacterQuery{}, nil
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context) (*model.GameQuery, error) {
	return &model.GameQuery{}, nil
}

// LookTypes is the resolver for the lookTypes field.
func (r *queryResolver) LookTypes(ctx context.Context) (*model.LookTypeQuery, error) {
	return &model.LookTypeQuery{}, nil
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context) (*model.MessageQuery, error) {
	return &model.MessageQuery{}, nil
}

// Moves is the resolver for the moves field.
func (r *queryResolver) Moves(ctx context.Context) (*model.MoveQuery, error) {
	return &model.MoveQuery{}, nil
}

// Scenarios is the resolver for the scenarios field.
func (r *queryResolver) Scenarios(ctx context.Context) (*model.ScenarioQuery, error) {
	return &model.ScenarioQuery{}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
